// Exports ABIs from Foundry build output into packages/shared so web and worker never hand-copy ABIs.
// Usage: (cd packages/contracts && forge build) && node scripts/export-abis.mjs
import { readFileSync, writeFileSync } from "node:fs";
const out = "packages/contracts/out";
const contracts = ["PayLightGateway", "CashbackRouter"];
let ts = "// AUTO-GENERATED by scripts/export-abis.mjs from packages/contracts/out. Do not edit.\n\n";
for (const name of contracts) {
  const { abi } = JSON.parse(readFileSync(`${out}/${name}.sol/${name}.json`, "utf8"));
  ts += `export const ${name[0].toLowerCase() + name.slice(1)}Abi = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
}
writeFileSync("packages/shared/src/abis.generated.ts", ts);
console.log("wrote packages/shared/src/abis.generated.ts");
